# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build artifact
      run: go build -o /home/runner/work/linux-x64 -v ./...

    - name: Test
      run: go test -v ./...
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-x64
        path: /home/runner/work/linux-x64

  build-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build artifact
      run: go build -o /home/runner/work/linux-arm64 -v ./...

    - name: Test
      run: go test -v ./...
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-arm64
        path: /home/runner/work/linux-arm64

  build-windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build artifact
      run: go build -o /home/runner/work/windows-x64 -v ./...

    - name: Test
      run: go test -v ./...
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-x64
        path: /home/runner/work/windows-x64

  build-windows-arm64:
    runs-on: 	windows-11-arm
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build artifact
      run: go build -o /home/runner/work/windows-arm64 -v ./...

    - name: Test
      run: go test -v ./...
    - name: upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-arm64
        path: /home/runner/work/windows-arm64
